### ISSUE TITLE
"AttributeError at /character/2/up 'int' object has no attribute 'pk'" lors du level up

### ISSUE THREAD

**Issue by Cegohal** [waliens/jdrhelper-server#3]
Erreur arrivé lors du level up avec comme new spell l'imposition des mains et 10 points supplémentaire en Force
![capture](https://cloud.githubusercontent.com/assets/24658549/22629122/942c15f2-ebe0-11e6-85ce-86d1bd52c2f1.PNG)

**Comment by Cegohal** [comment]
testé avec un autre sort et une autre stat, même erreur.

**Comment by waliens** [comment]
Fixed on server application
